package:
    name:           yii2-theme-adminlte
    namespace:      hiqdev\themes\adminlte
    headline:       Yii2 AdmniLte Theme
    title:          AdminLte Theme for hiqdev/yii2-thememanager
    type:           yii2-extension
    keywords:       adminlte, theme, extension, yii2
    year:           2014

require:
    hiqdev/hidev-config:        "*"
    hiqdev/hidev-config-php:    "*"
