parent:
    github:         hiqdev/hidev-config

package:
    name:           yii2-theme-adminlte
    namespace:      hiqdev\themes\adminlte
    title:          AdminLte Theme for hiqdev/yii2-thememanager
    type:           yii2-extension
    keywords:       adminlte, theme, extension, yii2
    year:           2014

composer.json:
    require:
        hiqdev/yii2-asset-adminlte:     "~2.1"
    extra:
        asset-installer-paths:
            npm-asset-library:          vendor/npm
            bower-asset-library:        vendor/bower
