package:
    type:           yii2-extension
    name:           yii2-theme-adminlte
    namespace:      hiqdev\themes\adminlte
    headline:       Yii2 AdmniLte Theme
    title:          AdminLte Theme for hiqdev/yii2-thememanager
    keywords:       adminlte, theme, extension, yii2

require:
    hiqdev/hidev-php:    "*"
    hiqdev/hidev-vendor: "*"
